<?php
$viewModel = $block->getData('view_model');

$collection = $block->getCollectionPosts();
?>

<?php if ($collection): ?>
    <div id="posts-list">
    <?php foreach ($collection as $_post):?>
        <div class="post-container">
            <a class="post-title" href="/<?= $viewModel->getUrl($_post->getId())?>"><?= $_post->getTitle()?></a>
            <div class="post-image">
<!--                <img src="--><?//= $_post['thumb'] ?><!--" alt="--><?//= $_post['title'] ?><!--">-->
            </div>
            <div class="post-time">
                <span><?= __('Data created: ') ?><?= $_post->getCreationTime() ?></span>
                <span><?= __('Data updated: ') ?><?= $_post->getUpdateTime() ?></span>
            </div>
            <div class="post-description"><?= $_post->getShortDescription() ?></div>
            <div class="post-author-name"><?= __('Author: ') ?><?= $_post->getAuthorName() ?></div>
        </div>
    <?php endforeach;?>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="blog-posts-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= __('No any record.'); ?></span></div>
<?php endif; ?>
